export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const COUNT_PHOTO = 'COUNT_PHOTO';
export const DECOUNT_PHOTO = 'DECOUNT_PHOTO';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const HOME_HEADER_BUTTON_CLICK = 'HOME_HEADER_BUTTON_CLICK';
